/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables;


import edu.baylor.cs.db.DefaultSchema;
import edu.baylor.cs.db.Keys;
import edu.baylor.cs.db.tables.Corporations.CorporationsPath;
import edu.baylor.cs.db.tables.Orders.OrdersPath;
import edu.baylor.cs.db.tables.Reservations.ReservationsPath;
import edu.baylor.cs.db.tables.Users.UsersPath;
import edu.baylor.cs.db.tables.records.BillsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Bills extends TableImpl<BillsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bills</code>
     */
    public static final Bills BILLS = new Bills();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BillsRecord> getRecordType() {
        return BillsRecord.class;
    }

    /**
     * The column <code>bills.id</code>.
     */
    public final TableField<BillsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>bills.user_id</code>.
     */
    public final TableField<BillsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bills.reservation_id</code>.
     */
    public final TableField<BillsRecord, Integer> RESERVATION_ID = createField(DSL.name("reservation_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bills.order_id</code>.
     */
    public final TableField<BillsRecord, Integer> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bills.total_amount</code>.
     */
    public final TableField<BillsRecord, Float> TOTAL_AMOUNT = createField(DSL.name("total_amount"), SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>bills.paid</code>.
     */
    public final TableField<BillsRecord, Integer> PAID = createField(DSL.name("paid"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>bills.corporation_id</code>.
     */
    public final TableField<BillsRecord, Integer> CORPORATION_ID = createField(DSL.name("corporation_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bills.created_at</code>.
     */
    public final TableField<BillsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>bills.paid_at</code>.
     */
    public final TableField<BillsRecord, LocalDateTime> PAID_AT = createField(DSL.name("paid_at"), SQLDataType.LOCALDATETIME(0), this, "");

    private Bills(Name alias, Table<BillsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Bills(Name alias, Table<BillsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bills</code> table reference
     */
    public Bills(String alias) {
        this(DSL.name(alias), BILLS);
    }

    /**
     * Create an aliased <code>bills</code> table reference
     */
    public Bills(Name alias) {
        this(alias, BILLS);
    }

    /**
     * Create a <code>bills</code> table reference
     */
    public Bills() {
        this(DSL.name("bills"), null);
    }

    public <O extends Record> Bills(Table<O> path, ForeignKey<O, BillsRecord> childPath, InverseForeignKey<O, BillsRecord> parentPath) {
        super(path, childPath, parentPath, BILLS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BillsPath extends Bills implements Path<BillsRecord> {
        public <O extends Record> BillsPath(Table<O> path, ForeignKey<O, BillsRecord> childPath, InverseForeignKey<O, BillsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BillsPath(Name alias, Table<BillsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BillsPath as(String alias) {
            return new BillsPath(DSL.name(alias), this);
        }

        @Override
        public BillsPath as(Name alias) {
            return new BillsPath(alias, this);
        }

        @Override
        public BillsPath as(Table<?> alias) {
            return new BillsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<BillsRecord, Integer> getIdentity() {
        return (Identity<BillsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BillsRecord> getPrimaryKey() {
        return Keys.BILLS__PK_BILLS;
    }

    @Override
    public List<ForeignKey<BillsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BILLS__FK_BILLS_PK_USERS, Keys.BILLS__FK_BILLS_PK_RESERVATIONS, Keys.BILLS__FK_BILLS_PK_ORDERS, Keys.BILLS__FK_BILLS_PK_CORPORATIONS);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.BILLS__FK_BILLS_PK_USERS, null);

        return _users;
    }

    private transient ReservationsPath _reservations;

    /**
     * Get the implicit join path to the <code>reservations</code> table.
     */
    public ReservationsPath reservations() {
        if (_reservations == null)
            _reservations = new ReservationsPath(this, Keys.BILLS__FK_BILLS_PK_RESERVATIONS, null);

        return _reservations;
    }

    private transient OrdersPath _orders;

    /**
     * Get the implicit join path to the <code>orders</code> table.
     */
    public OrdersPath orders() {
        if (_orders == null)
            _orders = new OrdersPath(this, Keys.BILLS__FK_BILLS_PK_ORDERS, null);

        return _orders;
    }

    private transient CorporationsPath _corporations;

    /**
     * Get the implicit join path to the <code>corporations</code> table.
     */
    public CorporationsPath corporations() {
        if (_corporations == null)
            _corporations = new CorporationsPath(this, Keys.BILLS__FK_BILLS_PK_CORPORATIONS, null);

        return _corporations;
    }

    @Override
    public Bills as(String alias) {
        return new Bills(DSL.name(alias), this);
    }

    @Override
    public Bills as(Name alias) {
        return new Bills(alias, this);
    }

    @Override
    public Bills as(Table<?> alias) {
        return new Bills(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bills rename(String name) {
        return new Bills(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bills rename(Name name) {
        return new Bills(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bills rename(Table<?> name) {
        return new Bills(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bills where(Condition condition) {
        return new Bills(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bills where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bills where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bills where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bills where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bills where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bills where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bills where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bills whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bills whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
