/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables;


import edu.baylor.cs.db.DefaultSchema;
import edu.baylor.cs.db.Keys;
import edu.baylor.cs.db.tables.Rooms.RoomsPath;
import edu.baylor.cs.db.tables.Users.UsersPath;
import edu.baylor.cs.db.tables.records.BookingsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Bookings extends TableImpl<BookingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bookings</code>
     */
    public static final Bookings BOOKINGS = new Bookings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookingsRecord> getRecordType() {
        return BookingsRecord.class;
    }

    /**
     * The column <code>bookings.id</code>.
     */
    public final TableField<BookingsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>bookings.user_id</code>.
     */
    public final TableField<BookingsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bookings.room_id</code>.
     */
    public final TableField<BookingsRecord, Integer> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bookings.start_time</code>.
     */
    public final TableField<BookingsRecord, LocalDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>bookings.end_time</code>.
     */
    public final TableField<BookingsRecord, LocalDateTime> END_TIME = createField(DSL.name("end_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>bookings.created_at</code>.
     */
    public final TableField<BookingsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Bookings(Name alias, Table<BookingsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Bookings(Name alias, Table<BookingsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bookings</code> table reference
     */
    public Bookings(String alias) {
        this(DSL.name(alias), BOOKINGS);
    }

    /**
     * Create an aliased <code>bookings</code> table reference
     */
    public Bookings(Name alias) {
        this(alias, BOOKINGS);
    }

    /**
     * Create a <code>bookings</code> table reference
     */
    public Bookings() {
        this(DSL.name("bookings"), null);
    }

    public <O extends Record> Bookings(Table<O> path, ForeignKey<O, BookingsRecord> childPath, InverseForeignKey<O, BookingsRecord> parentPath) {
        super(path, childPath, parentPath, BOOKINGS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BookingsPath extends Bookings implements Path<BookingsRecord> {
        public <O extends Record> BookingsPath(Table<O> path, ForeignKey<O, BookingsRecord> childPath, InverseForeignKey<O, BookingsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BookingsPath(Name alias, Table<BookingsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BookingsPath as(String alias) {
            return new BookingsPath(DSL.name(alias), this);
        }

        @Override
        public BookingsPath as(Name alias) {
            return new BookingsPath(alias, this);
        }

        @Override
        public BookingsPath as(Table<?> alias) {
            return new BookingsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<BookingsRecord, Integer> getIdentity() {
        return (Identity<BookingsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BookingsRecord> getPrimaryKey() {
        return Keys.BOOKINGS__PK_BOOKINGS;
    }

    @Override
    public List<ForeignKey<BookingsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BOOKINGS__FK_BOOKINGS_PK_USERS, Keys.BOOKINGS__FK_BOOKINGS_PK_ROOMS);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.BOOKINGS__FK_BOOKINGS_PK_USERS, null);

        return _users;
    }

    private transient RoomsPath _rooms;

    /**
     * Get the implicit join path to the <code>rooms</code> table.
     */
    public RoomsPath rooms() {
        if (_rooms == null)
            _rooms = new RoomsPath(this, Keys.BOOKINGS__FK_BOOKINGS_PK_ROOMS, null);

        return _rooms;
    }

    @Override
    public Bookings as(String alias) {
        return new Bookings(DSL.name(alias), this);
    }

    @Override
    public Bookings as(Name alias) {
        return new Bookings(alias, this);
    }

    @Override
    public Bookings as(Table<?> alias) {
        return new Bookings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookings rename(String name) {
        return new Bookings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookings rename(Name name) {
        return new Bookings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookings rename(Table<?> name) {
        return new Bookings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookings where(Condition condition) {
        return new Bookings(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookings whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookings whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
