/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables;


import edu.baylor.cs.db.DefaultSchema;
import edu.baylor.cs.db.Keys;
import edu.baylor.cs.db.tables.Bills.BillsPath;
import edu.baylor.cs.db.tables.GuestCorporations.GuestCorporationsPath;
import edu.baylor.cs.db.tables.Users.UsersPath;
import edu.baylor.cs.db.tables.records.CorporationsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Corporations extends TableImpl<CorporationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>corporations</code>
     */
    public static final Corporations CORPORATIONS = new Corporations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CorporationsRecord> getRecordType() {
        return CorporationsRecord.class;
    }

    /**
     * The column <code>corporations.id</code>.
     */
    public final TableField<CorporationsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>corporations.name</code>.
     */
    public final TableField<CorporationsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>corporations.billing_address</code>.
     */
    public final TableField<CorporationsRecord, String> BILLING_ADDRESS = createField(DSL.name("billing_address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>corporations.contact_email</code>.
     */
    public final TableField<CorporationsRecord, String> CONTACT_EMAIL = createField(DSL.name("contact_email"), SQLDataType.CLOB, this, "");

    private Corporations(Name alias, Table<CorporationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Corporations(Name alias, Table<CorporationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>corporations</code> table reference
     */
    public Corporations(String alias) {
        this(DSL.name(alias), CORPORATIONS);
    }

    /**
     * Create an aliased <code>corporations</code> table reference
     */
    public Corporations(Name alias) {
        this(alias, CORPORATIONS);
    }

    /**
     * Create a <code>corporations</code> table reference
     */
    public Corporations() {
        this(DSL.name("corporations"), null);
    }

    public <O extends Record> Corporations(Table<O> path, ForeignKey<O, CorporationsRecord> childPath, InverseForeignKey<O, CorporationsRecord> parentPath) {
        super(path, childPath, parentPath, CORPORATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CorporationsPath extends Corporations implements Path<CorporationsRecord> {
        public <O extends Record> CorporationsPath(Table<O> path, ForeignKey<O, CorporationsRecord> childPath, InverseForeignKey<O, CorporationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CorporationsPath(Name alias, Table<CorporationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CorporationsPath as(String alias) {
            return new CorporationsPath(DSL.name(alias), this);
        }

        @Override
        public CorporationsPath as(Name alias) {
            return new CorporationsPath(alias, this);
        }

        @Override
        public CorporationsPath as(Table<?> alias) {
            return new CorporationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<CorporationsRecord, Integer> getIdentity() {
        return (Identity<CorporationsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CorporationsRecord> getPrimaryKey() {
        return Keys.CORPORATIONS__PK_CORPORATIONS;
    }

    private transient BillsPath _bills;

    /**
     * Get the implicit to-many join path to the <code>bills</code> table
     */
    public BillsPath bills() {
        if (_bills == null)
            _bills = new BillsPath(this, null, Keys.BILLS__FK_BILLS_PK_CORPORATIONS.getInverseKey());

        return _bills;
    }

    private transient GuestCorporationsPath _guestCorporations;

    /**
     * Get the implicit to-many join path to the <code>guest_corporations</code>
     * table
     */
    public GuestCorporationsPath guestCorporations() {
        if (_guestCorporations == null)
            _guestCorporations = new GuestCorporationsPath(this, null, Keys.GUEST_CORPORATIONS__FK_GUEST_CORPORATIONS_PK_CORPORATIONS.getInverseKey());

        return _guestCorporations;
    }

    /**
     * Get the implicit many-to-many join path to the <code>users</code> table
     */
    public UsersPath users() {
        return guestCorporations().users();
    }

    @Override
    public Corporations as(String alias) {
        return new Corporations(DSL.name(alias), this);
    }

    @Override
    public Corporations as(Name alias) {
        return new Corporations(alias, this);
    }

    @Override
    public Corporations as(Table<?> alias) {
        return new Corporations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Corporations rename(String name) {
        return new Corporations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Corporations rename(Name name) {
        return new Corporations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Corporations rename(Table<?> name) {
        return new Corporations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Corporations where(Condition condition) {
        return new Corporations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Corporations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Corporations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Corporations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Corporations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Corporations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Corporations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Corporations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Corporations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Corporations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
