/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables;


import edu.baylor.cs.db.DefaultSchema;
import edu.baylor.cs.db.Keys;
import edu.baylor.cs.db.tables.Corporations.CorporationsPath;
import edu.baylor.cs.db.tables.Users.UsersPath;
import edu.baylor.cs.db.tables.records.GuestCorporationsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GuestCorporations extends TableImpl<GuestCorporationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>guest_corporations</code>
     */
    public static final GuestCorporations GUEST_CORPORATIONS = new GuestCorporations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuestCorporationsRecord> getRecordType() {
        return GuestCorporationsRecord.class;
    }

    /**
     * The column <code>guest_corporations.user_id</code>.
     */
    public final TableField<GuestCorporationsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>guest_corporations.corporation_id</code>.
     */
    public final TableField<GuestCorporationsRecord, Integer> CORPORATION_ID = createField(DSL.name("corporation_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private GuestCorporations(Name alias, Table<GuestCorporationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GuestCorporations(Name alias, Table<GuestCorporationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>guest_corporations</code> table reference
     */
    public GuestCorporations(String alias) {
        this(DSL.name(alias), GUEST_CORPORATIONS);
    }

    /**
     * Create an aliased <code>guest_corporations</code> table reference
     */
    public GuestCorporations(Name alias) {
        this(alias, GUEST_CORPORATIONS);
    }

    /**
     * Create a <code>guest_corporations</code> table reference
     */
    public GuestCorporations() {
        this(DSL.name("guest_corporations"), null);
    }

    public <O extends Record> GuestCorporations(Table<O> path, ForeignKey<O, GuestCorporationsRecord> childPath, InverseForeignKey<O, GuestCorporationsRecord> parentPath) {
        super(path, childPath, parentPath, GUEST_CORPORATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GuestCorporationsPath extends GuestCorporations implements Path<GuestCorporationsRecord> {
        public <O extends Record> GuestCorporationsPath(Table<O> path, ForeignKey<O, GuestCorporationsRecord> childPath, InverseForeignKey<O, GuestCorporationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GuestCorporationsPath(Name alias, Table<GuestCorporationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GuestCorporationsPath as(String alias) {
            return new GuestCorporationsPath(DSL.name(alias), this);
        }

        @Override
        public GuestCorporationsPath as(Name alias) {
            return new GuestCorporationsPath(alias, this);
        }

        @Override
        public GuestCorporationsPath as(Table<?> alias) {
            return new GuestCorporationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<GuestCorporationsRecord> getPrimaryKey() {
        return Keys.GUEST_CORPORATIONS__PK_GUEST_CORPORATIONS;
    }

    @Override
    public List<ForeignKey<GuestCorporationsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GUEST_CORPORATIONS__FK_GUEST_CORPORATIONS_PK_USERS, Keys.GUEST_CORPORATIONS__FK_GUEST_CORPORATIONS_PK_CORPORATIONS);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.GUEST_CORPORATIONS__FK_GUEST_CORPORATIONS_PK_USERS, null);

        return _users;
    }

    private transient CorporationsPath _corporations;

    /**
     * Get the implicit join path to the <code>corporations</code> table.
     */
    public CorporationsPath corporations() {
        if (_corporations == null)
            _corporations = new CorporationsPath(this, Keys.GUEST_CORPORATIONS__FK_GUEST_CORPORATIONS_PK_CORPORATIONS, null);

        return _corporations;
    }

    @Override
    public GuestCorporations as(String alias) {
        return new GuestCorporations(DSL.name(alias), this);
    }

    @Override
    public GuestCorporations as(Name alias) {
        return new GuestCorporations(alias, this);
    }

    @Override
    public GuestCorporations as(Table<?> alias) {
        return new GuestCorporations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuestCorporations rename(String name) {
        return new GuestCorporations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuestCorporations rename(Name name) {
        return new GuestCorporations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuestCorporations rename(Table<?> name) {
        return new GuestCorporations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GuestCorporations where(Condition condition) {
        return new GuestCorporations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GuestCorporations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GuestCorporations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GuestCorporations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GuestCorporations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GuestCorporations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GuestCorporations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GuestCorporations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GuestCorporations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GuestCorporations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
