/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables;


import edu.baylor.cs.db.DefaultSchema;
import edu.baylor.cs.db.Keys;
import edu.baylor.cs.db.tables.Bills.BillsPath;
import edu.baylor.cs.db.tables.Rooms.RoomsPath;
import edu.baylor.cs.db.tables.Users.UsersPath;
import edu.baylor.cs.db.tables.records.ReservationsRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Reservations extends TableImpl<ReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reservations</code>
     */
    public static final Reservations RESERVATIONS = new Reservations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReservationsRecord> getRecordType() {
        return ReservationsRecord.class;
    }

    /**
     * The column <code>reservations.id</code>.
     */
    public final TableField<ReservationsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>reservations.user_id</code>.
     */
    public final TableField<ReservationsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reservations.room_id</code>.
     */
    public final TableField<ReservationsRecord, Integer> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reservations.check_in_date</code>.
     */
    public final TableField<ReservationsRecord, LocalDate> CHECK_IN_DATE = createField(DSL.name("check_in_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>reservations.check_out_date</code>.
     */
    public final TableField<ReservationsRecord, LocalDate> CHECK_OUT_DATE = createField(DSL.name("check_out_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>reservations.rate</code>.
     */
    public final TableField<ReservationsRecord, Float> RATE = createField(DSL.name("rate"), SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>reservations.rate_type</code>.
     */
    public final TableField<ReservationsRecord, String> RATE_TYPE = createField(DSL.name("rate_type"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'STANDARD'"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>reservations.status</code>.
     */
    public final TableField<ReservationsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'CONFIRMED'"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>reservations.cancellation_fee</code>.
     */
    public final TableField<ReservationsRecord, Float> CANCELLATION_FEE = createField(DSL.name("cancellation_fee"), SQLDataType.REAL.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.REAL)), this, "");

    /**
     * The column <code>reservations.created_at</code>.
     */
    public final TableField<ReservationsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>reservations.cancelled_at</code>.
     */
    public final TableField<ReservationsRecord, LocalDateTime> CANCELLED_AT = createField(DSL.name("cancelled_at"), SQLDataType.LOCALDATETIME(0), this, "");

    private Reservations(Name alias, Table<ReservationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Reservations(Name alias, Table<ReservationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reservations</code> table reference
     */
    public Reservations(String alias) {
        this(DSL.name(alias), RESERVATIONS);
    }

    /**
     * Create an aliased <code>reservations</code> table reference
     */
    public Reservations(Name alias) {
        this(alias, RESERVATIONS);
    }

    /**
     * Create a <code>reservations</code> table reference
     */
    public Reservations() {
        this(DSL.name("reservations"), null);
    }

    public <O extends Record> Reservations(Table<O> path, ForeignKey<O, ReservationsRecord> childPath, InverseForeignKey<O, ReservationsRecord> parentPath) {
        super(path, childPath, parentPath, RESERVATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReservationsPath extends Reservations implements Path<ReservationsRecord> {
        public <O extends Record> ReservationsPath(Table<O> path, ForeignKey<O, ReservationsRecord> childPath, InverseForeignKey<O, ReservationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReservationsPath(Name alias, Table<ReservationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReservationsPath as(String alias) {
            return new ReservationsPath(DSL.name(alias), this);
        }

        @Override
        public ReservationsPath as(Name alias) {
            return new ReservationsPath(alias, this);
        }

        @Override
        public ReservationsPath as(Table<?> alias) {
            return new ReservationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ReservationsRecord, Integer> getIdentity() {
        return (Identity<ReservationsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReservationsRecord> getPrimaryKey() {
        return Keys.RESERVATIONS__PK_RESERVATIONS;
    }

    @Override
    public List<ForeignKey<ReservationsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RESERVATIONS__FK_RESERVATIONS_PK_USERS, Keys.RESERVATIONS__FK_RESERVATIONS_PK_ROOMS);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.RESERVATIONS__FK_RESERVATIONS_PK_USERS, null);

        return _users;
    }

    private transient RoomsPath _rooms;

    /**
     * Get the implicit join path to the <code>rooms</code> table.
     */
    public RoomsPath rooms() {
        if (_rooms == null)
            _rooms = new RoomsPath(this, Keys.RESERVATIONS__FK_RESERVATIONS_PK_ROOMS, null);

        return _rooms;
    }

    private transient BillsPath _bills;

    /**
     * Get the implicit to-many join path to the <code>bills</code> table
     */
    public BillsPath bills() {
        if (_bills == null)
            _bills = new BillsPath(this, null, Keys.BILLS__FK_BILLS_PK_RESERVATIONS.getInverseKey());

        return _bills;
    }

    @Override
    public Reservations as(String alias) {
        return new Reservations(DSL.name(alias), this);
    }

    @Override
    public Reservations as(Name alias) {
        return new Reservations(alias, this);
    }

    @Override
    public Reservations as(Table<?> alias) {
        return new Reservations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reservations rename(String name) {
        return new Reservations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reservations rename(Name name) {
        return new Reservations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reservations rename(Table<?> name) {
        return new Reservations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Condition condition) {
        return new Reservations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reservations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reservations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
