/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables;


import edu.baylor.cs.db.DefaultSchema;
import edu.baylor.cs.db.Keys;
import edu.baylor.cs.db.tables.Reservations.ReservationsPath;
import edu.baylor.cs.db.tables.records.RoomsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rooms extends TableImpl<RoomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rooms</code>
     */
    public static final Rooms ROOMS = new Rooms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomsRecord> getRecordType() {
        return RoomsRecord.class;
    }

    /**
     * The column <code>rooms.id</code>.
     */
    public final TableField<RoomsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>rooms.room_number</code>.
     */
    public final TableField<RoomsRecord, String> ROOM_NUMBER = createField(DSL.name("room_number"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rooms.floor</code>.
     */
    public final TableField<RoomsRecord, Integer> FLOOR = createField(DSL.name("floor"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rooms.room_type</code>.
     */
    public final TableField<RoomsRecord, String> ROOM_TYPE = createField(DSL.name("room_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rooms.quality_level</code>.
     */
    public final TableField<RoomsRecord, String> QUALITY_LEVEL = createField(DSL.name("quality_level"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rooms.bed_type</code>.
     */
    public final TableField<RoomsRecord, String> BED_TYPE = createField(DSL.name("bed_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rooms.num_beds</code>.
     */
    public final TableField<RoomsRecord, Integer> NUM_BEDS = createField(DSL.name("num_beds"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>rooms.smoking</code>.
     */
    public final TableField<RoomsRecord, Integer> SMOKING = createField(DSL.name("smoking"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>rooms.daily_rate</code>.
     */
    public final TableField<RoomsRecord, Float> DAILY_RATE = createField(DSL.name("daily_rate"), SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>rooms.description</code>.
     */
    public final TableField<RoomsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rooms.status</code>.
     */
    public final TableField<RoomsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'AVAILABLE'"), SQLDataType.CLOB)), this, "");

    private Rooms(Name alias, Table<RoomsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Rooms(Name alias, Table<RoomsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rooms</code> table reference
     */
    public Rooms(String alias) {
        this(DSL.name(alias), ROOMS);
    }

    /**
     * Create an aliased <code>rooms</code> table reference
     */
    public Rooms(Name alias) {
        this(alias, ROOMS);
    }

    /**
     * Create a <code>rooms</code> table reference
     */
    public Rooms() {
        this(DSL.name("rooms"), null);
    }

    public <O extends Record> Rooms(Table<O> path, ForeignKey<O, RoomsRecord> childPath, InverseForeignKey<O, RoomsRecord> parentPath) {
        super(path, childPath, parentPath, ROOMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoomsPath extends Rooms implements Path<RoomsRecord> {
        public <O extends Record> RoomsPath(Table<O> path, ForeignKey<O, RoomsRecord> childPath, InverseForeignKey<O, RoomsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoomsPath(Name alias, Table<RoomsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoomsPath as(String alias) {
            return new RoomsPath(DSL.name(alias), this);
        }

        @Override
        public RoomsPath as(Name alias) {
            return new RoomsPath(alias, this);
        }

        @Override
        public RoomsPath as(Table<?> alias) {
            return new RoomsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<RoomsRecord, Integer> getIdentity() {
        return (Identity<RoomsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoomsRecord> getPrimaryKey() {
        return Keys.ROOMS__PK_ROOMS;
    }

    @Override
    public List<UniqueKey<RoomsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ROOMS__UK_ROOMS_5607445);
    }

    private transient ReservationsPath _reservations;

    /**
     * Get the implicit to-many join path to the <code>reservations</code> table
     */
    public ReservationsPath reservations() {
        if (_reservations == null)
            _reservations = new ReservationsPath(this, null, Keys.RESERVATIONS__FK_RESERVATIONS_PK_ROOMS.getInverseKey());

        return _reservations;
    }

    @Override
    public Rooms as(String alias) {
        return new Rooms(DSL.name(alias), this);
    }

    @Override
    public Rooms as(Name alias) {
        return new Rooms(alias, this);
    }

    @Override
    public Rooms as(Table<?> alias) {
        return new Rooms(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rooms rename(String name) {
        return new Rooms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rooms rename(Name name) {
        return new Rooms(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rooms rename(Table<?> name) {
        return new Rooms(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Condition condition) {
        return new Rooms(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
