/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Bills;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BillsRecord extends UpdatableRecordImpl<BillsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bills.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bills.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bills.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bills.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bills.reservation_id</code>.
     */
    public void setReservationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bills.reservation_id</code>.
     */
    public Integer getReservationId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bills.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>bills.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>bills.total_amount</code>.
     */
    public void setTotalAmount(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>bills.total_amount</code>.
     */
    public Float getTotalAmount() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>bills.paid</code>.
     */
    public void setPaid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bills.paid</code>.
     */
    public Integer getPaid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bills.corporation_id</code>.
     */
    public void setCorporationId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>bills.corporation_id</code>.
     */
    public Integer getCorporationId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>bills.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>bills.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>bills.paid_at</code>.
     */
    public void setPaidAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>bills.paid_at</code>.
     */
    public LocalDateTime getPaidAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BillsRecord
     */
    public BillsRecord() {
        super(Bills.BILLS);
    }

    /**
     * Create a detached, initialised BillsRecord
     */
    public BillsRecord(Integer id, Integer userId, Integer reservationId, Integer orderId, Float totalAmount, Integer paid, Integer corporationId, LocalDateTime createdAt, LocalDateTime paidAt) {
        super(Bills.BILLS);

        setId(id);
        setUserId(userId);
        setReservationId(reservationId);
        setOrderId(orderId);
        setTotalAmount(totalAmount);
        setPaid(paid);
        setCorporationId(corporationId);
        setCreatedAt(createdAt);
        setPaidAt(paidAt);
        resetChangedOnNotNull();
    }
}
