/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Bookings;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookingsRecord extends UpdatableRecordImpl<BookingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bookings.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bookings.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bookings.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bookings.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bookings.room_id</code>.
     */
    public void setRoomId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bookings.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bookings.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>bookings.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>bookings.end_time</code>.
     */
    public void setEndTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>bookings.end_time</code>.
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>bookings.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>bookings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingsRecord
     */
    public BookingsRecord() {
        super(Bookings.BOOKINGS);
    }

    /**
     * Create a detached, initialised BookingsRecord
     */
    public BookingsRecord(Integer id, Integer userId, Integer roomId, LocalDateTime startTime, LocalDateTime endTime, LocalDateTime createdAt) {
        super(Bookings.BOOKINGS);

        setId(id);
        setUserId(userId);
        setRoomId(roomId);
        setStartTime(startTime);
        setEndTime(endTime);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
