/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Corporations;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CorporationsRecord extends UpdatableRecordImpl<CorporationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>corporations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>corporations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>corporations.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>corporations.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>corporations.billing_address</code>.
     */
    public void setBillingAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>corporations.billing_address</code>.
     */
    public String getBillingAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>corporations.contact_email</code>.
     */
    public void setContactEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>corporations.contact_email</code>.
     */
    public String getContactEmail() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CorporationsRecord
     */
    public CorporationsRecord() {
        super(Corporations.CORPORATIONS);
    }

    /**
     * Create a detached, initialised CorporationsRecord
     */
    public CorporationsRecord(Integer id, String name, String billingAddress, String contactEmail) {
        super(Corporations.CORPORATIONS);

        setId(id);
        setName(name);
        setBillingAddress(billingAddress);
        setContactEmail(contactEmail);
        resetChangedOnNotNull();
    }
}
