/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.GuestCorporations;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GuestCorporationsRecord extends UpdatableRecordImpl<GuestCorporationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>guest_corporations.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>guest_corporations.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>guest_corporations.corporation_id</code>.
     */
    public void setCorporationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>guest_corporations.corporation_id</code>.
     */
    public Integer getCorporationId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuestCorporationsRecord
     */
    public GuestCorporationsRecord() {
        super(GuestCorporations.GUEST_CORPORATIONS);
    }

    /**
     * Create a detached, initialised GuestCorporationsRecord
     */
    public GuestCorporationsRecord(Integer userId, Integer corporationId) {
        super(GuestCorporations.GUEST_CORPORATIONS);

        setUserId(userId);
        setCorporationId(corporationId);
        resetChangedOnNotNull();
    }
}
