/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Orders;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orders.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>orders.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>orders.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>orders.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>orders.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>orders.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>orders.purchased_at</code>.
     */
    public void setPurchasedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>orders.purchased_at</code>.
     */
    public LocalDateTime getPurchasedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer id, Integer userId, String status, LocalDateTime createdAt, LocalDateTime purchasedAt) {
        super(Orders.ORDERS);

        setId(id);
        setUserId(userId);
        setStatus(status);
        setCreatedAt(createdAt);
        setPurchasedAt(purchasedAt);
        resetChangedOnNotNull();
    }
}
