/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Products;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>products.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>products.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>products.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>products.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>products.category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>products.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>products.price</code>.
     */
    public void setPrice(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>products.price</code>.
     */
    public Float getPrice() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>products.stock_quantity</code>.
     */
    public void setStockQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>products.stock_quantity</code>.
     */
    public Integer getStockQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>products.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>products.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(Integer id, String name, String category, Float price, Integer stockQuantity, String description) {
        super(Products.PRODUCTS);

        setId(id);
        setName(name);
        setCategory(category);
        setPrice(price);
        setStockQuantity(stockQuantity);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
