/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Reservations;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservationsRecord extends UpdatableRecordImpl<ReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reservations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reservations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reservations.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reservations.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reservations.room_id</code>.
     */
    public void setRoomId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>reservations.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>reservations.check_in_date</code>.
     */
    public void setCheckInDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>reservations.check_in_date</code>.
     */
    public LocalDate getCheckInDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>reservations.check_out_date</code>.
     */
    public void setCheckOutDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>reservations.check_out_date</code>.
     */
    public LocalDate getCheckOutDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>reservations.rate</code>.
     */
    public void setRate(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>reservations.rate</code>.
     */
    public Float getRate() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>reservations.rate_type</code>.
     */
    public void setRateType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>reservations.rate_type</code>.
     */
    public String getRateType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>reservations.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>reservations.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>reservations.cancellation_fee</code>.
     */
    public void setCancellationFee(Float value) {
        set(8, value);
    }

    /**
     * Getter for <code>reservations.cancellation_fee</code>.
     */
    public Float getCancellationFee() {
        return (Float) get(8);
    }

    /**
     * Setter for <code>reservations.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>reservations.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>reservations.cancelled_at</code>.
     */
    public void setCancelledAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>reservations.cancelled_at</code>.
     */
    public LocalDateTime getCancelledAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationsRecord
     */
    public ReservationsRecord() {
        super(Reservations.RESERVATIONS);
    }

    /**
     * Create a detached, initialised ReservationsRecord
     */
    public ReservationsRecord(Integer id, Integer userId, Integer roomId, LocalDate checkInDate, LocalDate checkOutDate, Float rate, String rateType, String status, Float cancellationFee, LocalDateTime createdAt, LocalDateTime cancelledAt) {
        super(Reservations.RESERVATIONS);

        setId(id);
        setUserId(userId);
        setRoomId(roomId);
        setCheckInDate(checkInDate);
        setCheckOutDate(checkOutDate);
        setRate(rate);
        setRateType(rateType);
        setStatus(status);
        setCancellationFee(cancellationFee);
        setCreatedAt(createdAt);
        setCancelledAt(cancelledAt);
        resetChangedOnNotNull();
    }
}
