/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Rooms;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomsRecord extends UpdatableRecordImpl<RoomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rooms.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rooms.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rooms.room_number</code>.
     */
    public void setRoomNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rooms.room_number</code>.
     */
    public String getRoomNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rooms.floor</code>.
     */
    public void setFloor(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rooms.floor</code>.
     */
    public Integer getFloor() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rooms.room_type</code>.
     */
    public void setRoomType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rooms.room_type</code>.
     */
    public String getRoomType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rooms.quality_level</code>.
     */
    public void setQualityLevel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rooms.quality_level</code>.
     */
    public String getQualityLevel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rooms.bed_type</code>.
     */
    public void setBedType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rooms.bed_type</code>.
     */
    public String getBedType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rooms.num_beds</code>.
     */
    public void setNumBeds(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>rooms.num_beds</code>.
     */
    public Integer getNumBeds() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>rooms.smoking</code>.
     */
    public void setSmoking(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>rooms.smoking</code>.
     */
    public Integer getSmoking() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>rooms.daily_rate</code>.
     */
    public void setDailyRate(Float value) {
        set(8, value);
    }

    /**
     * Getter for <code>rooms.daily_rate</code>.
     */
    public Float getDailyRate() {
        return (Float) get(8);
    }

    /**
     * Setter for <code>rooms.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>rooms.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>rooms.status</code>.
     */
    public void setStatus(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>rooms.status</code>.
     */
    public String getStatus() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomsRecord
     */
    public RoomsRecord() {
        super(Rooms.ROOMS);
    }

    /**
     * Create a detached, initialised RoomsRecord
     */
    public RoomsRecord(Integer id, String roomNumber, Integer floor, String roomType, String qualityLevel, String bedType, Integer numBeds, Integer smoking, Float dailyRate, String description, String status) {
        super(Rooms.ROOMS);

        setId(id);
        setRoomNumber(roomNumber);
        setFloor(floor);
        setRoomType(roomType);
        setQualityLevel(qualityLevel);
        setBedType(bedType);
        setNumBeds(numBeds);
        setSmoking(smoking);
        setDailyRate(dailyRate);
        setDescription(description);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
