/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db.tables.records;


import edu.baylor.cs.db.tables.Rooms;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomsRecord extends UpdatableRecordImpl<RoomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rooms.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rooms.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rooms.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rooms.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rooms.capacity</code>.
     */
    public void setCapacity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rooms.capacity</code>.
     */
    public Integer getCapacity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rooms.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rooms.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomsRecord
     */
    public RoomsRecord() {
        super(Rooms.ROOMS);
    }

    /**
     * Create a detached, initialised RoomsRecord
     */
    public RoomsRecord(Integer id, String name, Integer capacity, String description) {
        super(Rooms.ROOMS);

        setId(id);
        setName(name);
        setCapacity(capacity);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
