/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db;


import edu.baylor.cs.db.tables.Bills;
import edu.baylor.cs.db.tables.Corporations;
import edu.baylor.cs.db.tables.GuestCorporations;
import edu.baylor.cs.db.tables.OrderItems;
import edu.baylor.cs.db.tables.Orders;
import edu.baylor.cs.db.tables.Products;
import edu.baylor.cs.db.tables.Reservations;
import edu.baylor.cs.db.tables.Rooms;
import edu.baylor.cs.db.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>bills</code>.
     */
    public final Bills BILLS = Bills.BILLS;

    /**
     * The table <code>corporations</code>.
     */
    public final Corporations CORPORATIONS = Corporations.CORPORATIONS;

    /**
     * The table <code>guest_corporations</code>.
     */
    public final GuestCorporations GUEST_CORPORATIONS = GuestCorporations.GUEST_CORPORATIONS;

    /**
     * The table <code>order_items</code>.
     */
    public final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>reservations</code>.
     */
    public final Reservations RESERVATIONS = Reservations.RESERVATIONS;

    /**
     * The table <code>rooms</code>.
     */
    public final Rooms ROOMS = Rooms.ROOMS;

    /**
     * The table <code>users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Bills.BILLS,
            Corporations.CORPORATIONS,
            GuestCorporations.GUEST_CORPORATIONS,
            OrderItems.ORDER_ITEMS,
            Orders.ORDERS,
            Products.PRODUCTS,
            Reservations.RESERVATIONS,
            Rooms.ROOMS,
            Users.USERS
        );
    }
}
