/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db;


import edu.baylor.cs.db.tables.Bookings;
import edu.baylor.cs.db.tables.Rooms;
import edu.baylor.cs.db.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>bookings</code>.
     */
    public final Bookings BOOKINGS = Bookings.BOOKINGS;

    /**
     * The table <code>rooms</code>.
     */
    public final Rooms ROOMS = Rooms.ROOMS;

    /**
     * The table <code>users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Bookings.BOOKINGS,
            Rooms.ROOMS,
            Users.USERS
        );
    }
}
