/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db;


import edu.baylor.cs.db.tables.Bookings;
import edu.baylor.cs.db.tables.Rooms;
import edu.baylor.cs.db.tables.Users;
import edu.baylor.cs.db.tables.records.BookingsRecord;
import edu.baylor.cs.db.tables.records.RoomsRecord;
import edu.baylor.cs.db.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BookingsRecord> BOOKINGS__PK_BOOKINGS = Internal.createUniqueKey(Bookings.BOOKINGS, DSL.name("pk_bookings"), new TableField[] { Bookings.BOOKINGS.ID }, true);
    public static final UniqueKey<RoomsRecord> ROOMS__PK_ROOMS = Internal.createUniqueKey(Rooms.ROOMS, DSL.name("pk_rooms"), new TableField[] { Rooms.ROOMS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS__PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk_users"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS__UK_USERS_116436086 = Internal.createUniqueKey(Users.USERS, DSL.name("uk_users_116436086"), new TableField[] { Users.USERS.EMAIL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BookingsRecord, RoomsRecord> BOOKINGS__FK_BOOKINGS_PK_ROOMS = Internal.createForeignKey(Bookings.BOOKINGS, DSL.name("fk_bookings_pk_rooms"), new TableField[] { Bookings.BOOKINGS.ROOM_ID }, Keys.ROOMS__PK_ROOMS, new TableField[] { Rooms.ROOMS.ID }, true);
    public static final ForeignKey<BookingsRecord, UsersRecord> BOOKINGS__FK_BOOKINGS_PK_USERS = Internal.createForeignKey(Bookings.BOOKINGS, DSL.name("fk_bookings_pk_users"), new TableField[] { Bookings.BOOKINGS.USER_ID }, Keys.USERS__PK_USERS, new TableField[] { Users.USERS.ID }, true);
}
