/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db;


import edu.baylor.cs.db.tables.Bills;
import edu.baylor.cs.db.tables.Corporations;
import edu.baylor.cs.db.tables.GuestCorporations;
import edu.baylor.cs.db.tables.OrderItems;
import edu.baylor.cs.db.tables.Orders;
import edu.baylor.cs.db.tables.Products;
import edu.baylor.cs.db.tables.Reservations;
import edu.baylor.cs.db.tables.Rooms;
import edu.baylor.cs.db.tables.Users;
import edu.baylor.cs.db.tables.records.BillsRecord;
import edu.baylor.cs.db.tables.records.CorporationsRecord;
import edu.baylor.cs.db.tables.records.GuestCorporationsRecord;
import edu.baylor.cs.db.tables.records.OrderItemsRecord;
import edu.baylor.cs.db.tables.records.OrdersRecord;
import edu.baylor.cs.db.tables.records.ProductsRecord;
import edu.baylor.cs.db.tables.records.ReservationsRecord;
import edu.baylor.cs.db.tables.records.RoomsRecord;
import edu.baylor.cs.db.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BillsRecord> BILLS__PK_BILLS = Internal.createUniqueKey(Bills.BILLS, DSL.name("pk_bills"), new TableField[] { Bills.BILLS.ID }, true);
    public static final UniqueKey<CorporationsRecord> CORPORATIONS__PK_CORPORATIONS = Internal.createUniqueKey(Corporations.CORPORATIONS, DSL.name("pk_corporations"), new TableField[] { Corporations.CORPORATIONS.ID }, true);
    public static final UniqueKey<GuestCorporationsRecord> GUEST_CORPORATIONS__PK_GUEST_CORPORATIONS = Internal.createUniqueKey(GuestCorporations.GUEST_CORPORATIONS, DSL.name("pk_guest_corporations"), new TableField[] { GuestCorporations.GUEST_CORPORATIONS.USER_ID, GuestCorporations.GUEST_CORPORATIONS.CORPORATION_ID }, true);
    public static final UniqueKey<OrderItemsRecord> ORDER_ITEMS__PK_ORDER_ITEMS = Internal.createUniqueKey(OrderItems.ORDER_ITEMS, DSL.name("pk_order_items"), new TableField[] { OrderItems.ORDER_ITEMS.ID }, true);
    public static final UniqueKey<OrdersRecord> ORDERS__PK_ORDERS = Internal.createUniqueKey(Orders.ORDERS, DSL.name("pk_orders"), new TableField[] { Orders.ORDERS.ID }, true);
    public static final UniqueKey<ProductsRecord> PRODUCTS__PK_PRODUCTS = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("pk_products"), new TableField[] { Products.PRODUCTS.ID }, true);
    public static final UniqueKey<ReservationsRecord> RESERVATIONS__PK_RESERVATIONS = Internal.createUniqueKey(Reservations.RESERVATIONS, DSL.name("pk_reservations"), new TableField[] { Reservations.RESERVATIONS.ID }, true);
    public static final UniqueKey<RoomsRecord> ROOMS__PK_ROOMS = Internal.createUniqueKey(Rooms.ROOMS, DSL.name("pk_rooms"), new TableField[] { Rooms.ROOMS.ID }, true);
    public static final UniqueKey<RoomsRecord> ROOMS__UK_ROOMS_5607445 = Internal.createUniqueKey(Rooms.ROOMS, DSL.name("uk_rooms_5607445"), new TableField[] { Rooms.ROOMS.ROOM_NUMBER }, true);
    public static final UniqueKey<UsersRecord> USERS__PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk_users"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS__UK_USERS_3307420 = Internal.createUniqueKey(Users.USERS, DSL.name("uk_users_3307420"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BillsRecord, CorporationsRecord> BILLS__FK_BILLS_PK_CORPORATIONS = Internal.createForeignKey(Bills.BILLS, DSL.name("fk_bills_pk_corporations"), new TableField[] { Bills.BILLS.CORPORATION_ID }, Keys.CORPORATIONS__PK_CORPORATIONS, new TableField[] { Corporations.CORPORATIONS.ID }, true);
    public static final ForeignKey<BillsRecord, OrdersRecord> BILLS__FK_BILLS_PK_ORDERS = Internal.createForeignKey(Bills.BILLS, DSL.name("fk_bills_pk_orders"), new TableField[] { Bills.BILLS.ORDER_ID }, Keys.ORDERS__PK_ORDERS, new TableField[] { Orders.ORDERS.ID }, true);
    public static final ForeignKey<BillsRecord, ReservationsRecord> BILLS__FK_BILLS_PK_RESERVATIONS = Internal.createForeignKey(Bills.BILLS, DSL.name("fk_bills_pk_reservations"), new TableField[] { Bills.BILLS.RESERVATION_ID }, Keys.RESERVATIONS__PK_RESERVATIONS, new TableField[] { Reservations.RESERVATIONS.ID }, true);
    public static final ForeignKey<BillsRecord, UsersRecord> BILLS__FK_BILLS_PK_USERS = Internal.createForeignKey(Bills.BILLS, DSL.name("fk_bills_pk_users"), new TableField[] { Bills.BILLS.USER_ID }, Keys.USERS__PK_USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<GuestCorporationsRecord, CorporationsRecord> GUEST_CORPORATIONS__FK_GUEST_CORPORATIONS_PK_CORPORATIONS = Internal.createForeignKey(GuestCorporations.GUEST_CORPORATIONS, DSL.name("fk_guest_corporations_pk_corporations"), new TableField[] { GuestCorporations.GUEST_CORPORATIONS.CORPORATION_ID }, Keys.CORPORATIONS__PK_CORPORATIONS, new TableField[] { Corporations.CORPORATIONS.ID }, true);
    public static final ForeignKey<GuestCorporationsRecord, UsersRecord> GUEST_CORPORATIONS__FK_GUEST_CORPORATIONS_PK_USERS = Internal.createForeignKey(GuestCorporations.GUEST_CORPORATIONS, DSL.name("fk_guest_corporations_pk_users"), new TableField[] { GuestCorporations.GUEST_CORPORATIONS.USER_ID }, Keys.USERS__PK_USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<OrderItemsRecord, OrdersRecord> ORDER_ITEMS__FK_ORDER_ITEMS_PK_ORDERS = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("fk_order_items_pk_orders"), new TableField[] { OrderItems.ORDER_ITEMS.ORDER_ID }, Keys.ORDERS__PK_ORDERS, new TableField[] { Orders.ORDERS.ID }, true);
    public static final ForeignKey<OrderItemsRecord, ProductsRecord> ORDER_ITEMS__FK_ORDER_ITEMS_PK_PRODUCTS = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("fk_order_items_pk_products"), new TableField[] { OrderItems.ORDER_ITEMS.PRODUCT_ID }, Keys.PRODUCTS__PK_PRODUCTS, new TableField[] { Products.PRODUCTS.ID }, true);
    public static final ForeignKey<OrdersRecord, UsersRecord> ORDERS__FK_ORDERS_PK_USERS = Internal.createForeignKey(Orders.ORDERS, DSL.name("fk_orders_pk_users"), new TableField[] { Orders.ORDERS.USER_ID }, Keys.USERS__PK_USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ReservationsRecord, RoomsRecord> RESERVATIONS__FK_RESERVATIONS_PK_ROOMS = Internal.createForeignKey(Reservations.RESERVATIONS, DSL.name("fk_reservations_pk_rooms"), new TableField[] { Reservations.RESERVATIONS.ROOM_ID }, Keys.ROOMS__PK_ROOMS, new TableField[] { Rooms.ROOMS.ID }, true);
    public static final ForeignKey<ReservationsRecord, UsersRecord> RESERVATIONS__FK_RESERVATIONS_PK_USERS = Internal.createForeignKey(Reservations.RESERVATIONS, DSL.name("fk_reservations_pk_users"), new TableField[] { Reservations.RESERVATIONS.USER_ID }, Keys.USERS__PK_USERS, new TableField[] { Users.USERS.ID }, true);
}
