/*
 * This file is generated by jOOQ.
 */
package edu.baylor.cs.db;


import edu.baylor.cs.db.tables.Bookings;
import edu.baylor.cs.db.tables.Rooms;
import edu.baylor.cs.db.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>bookings</code>.
     */
    public static final Bookings BOOKINGS = Bookings.BOOKINGS;

    /**
     * The table <code>rooms</code>.
     */
    public static final Rooms ROOMS = Rooms.ROOMS;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
